added path to defaultWatermark error

diff --git a/addwatermark b/addwatermark
--- a/addwatermark
+++ b/addwatermark
@@ -42,7 +42,7 @@ if [ "$watermarkFile" == "" ]; then
 	if [ -f "$defaultWatermark" ]; then
 		watermarkFile=$defaultWatermark
 	else
-		echo "default watermark file not found" >&2
+		echo "default watermark file not found at $defaultWatermark" >&2
 		exit 2
 	fi
 fi
